import { Time } from '../model/time.model';

export const teams: Time[] = [
  {
    idTime: 1,
    nomeTime: 'América-MG',
    forcaAtaque: 3,
    forcaDefesa: 2,
    torcida: 4,
    estadio: 'Estádio Independência',
    capacidadeEstadio: 23018,
    financas: 3,
    idolo: 'Reinaldo',
    nomeCompleto: 'América Futebol Clube',
    titulos: {
      estadual: 16,
      brasileirao: 0,
      copaDoBrasil: 0,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [
      {
        idJogador: 1,
        idTime: 1,
        nomeJogador: 'Júlio',
        idadeJogador: 28,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 50000,
        golsJogador: 0,
        forcaJogador: 80,
      },
      {
        idJogador: 2,
        idTime: 1,
        nomeJogador: 'Anderson',
        idadeJogador: 26,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 85,
      },
      {
        idJogador: 3,
        idTime: 1,
        nomeJogador: 'Lucas',
        idadeJogador: 24,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 75000,
        golsJogador: 2,
        forcaJogador: 84,
      },
      {
        idJogador: 4,
        idTime: 1,
        nomeJogador: 'Rafael',
        idadeJogador: 27,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 70000,
        golsJogador: 5,
        forcaJogador: 82,
      },
      {
        idJogador: 5,
        idTime: 1,
        nomeJogador: 'Fernando',
        idadeJogador: 25,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 72000,
        golsJogador: 7,
        forcaJogador: 83,
      },
      {
        idJogador: 6,
        idTime: 1,
        nomeJogador: 'Carlos',
        idadeJogador: 29,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Fin/Pas',
        valorJogador: 90000,
        golsJogador: 12,
        forcaJogador: 88,
      },
      {
        idJogador: 7,
        idTime: 1,
        nomeJogador: 'Pedro',
        idadeJogador: 24,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 82000,
        golsJogador: 8,
        forcaJogador: 84,
      },
      {
        idJogador: 8,
        idTime: 1,
        nomeJogador: 'Gustavo',
        idadeJogador: 26,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 85000,
        golsJogador: 10,
        forcaJogador: 86,
      },
      {
        idJogador: 9,
        idTime: 1,
        nomeJogador: 'Mariana',
        idadeJogador: 23,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Vel/Fin',
        valorJogador: 78000,
        golsJogador: 6,
        forcaJogador: 81,
      },
      {
        idJogador: 10,
        idTime: 1,
        nomeJogador: 'João',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 40,
        forcaJogador: 90,
      },
      {
        idJogador: 11,
        idTime: 1,
        nomeJogador: 'Laura',
        idadeJogador: 28,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 92000,
        golsJogador: 35,
        forcaJogador: 88,
      },
    ],
  },
  {
    idTime: 2,
    nomeTime: 'Athletico-PR',
    forcaAtaque: 5,
    forcaDefesa: 2,
    torcida: 6,
    estadio: 'Arena da Baixada',
    capacidadeEstadio: 42300,
    financas: 6,
    idolo: 'Thiago Heleno',
    nomeCompleto: 'Club Athletico Paranaense',
    titulos: {
      estadual: 10,
      brasileirao: 1,
      copaDoBrasil: 1,
      libertadores: 1,
      mundial: 0,
    },
    jogadores: [
      {
        idJogador: 12,
        idTime: 2,
        nomeJogador: 'Santos',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 90000,
        golsJogador: 0,
        forcaJogador: 88,
      },
      {
        idJogador: 13,
        idTime: 2,
        nomeJogador: 'Pedro Henrique',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 75000,
        golsJogador: 2,
        forcaJogador: 83,
      },
      {
        idJogador: 14,
        idTime: 2,
        nomeJogador: 'Abner',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 85,
      },
      {
        idJogador: 15,
        idTime: 2,
        nomeJogador: 'Nikão',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Fin/Pas',
        valorJogador: 85000,
        golsJogador: 8,
        forcaJogador: 86,
      },
      {
        idJogador: 16,
        idTime: 2,
        nomeJogador: 'David Terans',
        idadeJogador: 26,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 82000,
        golsJogador: 7,
        forcaJogador: 84,
      },
      {
        idJogador: 17,
        idTime: 2,
        nomeJogador: 'Renato Kayzer',
        idadeJogador: 26,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 90000,
        golsJogador: 10,
        forcaJogador: 88,
      },
      {
        idJogador: 18,
        idTime: 2,
        nomeJogador: 'Vitinho',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 85000,
        golsJogador: 9,
        forcaJogador: 86,
      },
      {
        idJogador: 19,
        idTime: 2,
        nomeJogador: 'Matheus Babi',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 88000,
        golsJogador: 12,
        forcaJogador: 87,
      },
      {
        idJogador: 20,
        idTime: 2,
        nomeJogador: 'Richard',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 78000,
        golsJogador: 5,
        forcaJogador: 82,
      },
      {
        idJogador: 21,
        idTime: 2,
        nomeJogador: 'Lucas Halter',
        idadeJogador: 22,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 70000,
        golsJogador: 1,
        forcaJogador: 80,
      },
      {
        idJogador: 22,
        idTime: 2,
        nomeJogador: 'Carlos Eduardo',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 82000,
        golsJogador: 6,
        forcaJogador: 84,
      },
    ],
  },
  {
    idTime: 3,
    nomeTime: 'Atlético-MG',
    forcaAtaque: 8,
    forcaDefesa: 4,
    torcida: 8,
    estadio: 'Mineirão',
    capacidadeEstadio: 61846,
    financas: 8,
    idolo: 'Reinaldo',
    nomeCompleto: 'Clube Atlético Mineiro',
    titulos: {
      estadual: 47,
      brasileirao: 1,
      copaDoBrasil: 1,
      libertadores: 1,
      mundial: 1,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
  {
    idTime: 4,
    nomeTime: 'Bahia',
    forcaAtaque: 4,
    forcaDefesa: 3,
    torcida: 5,
    estadio: 'Arena Fonte Nova',
    capacidadeEstadio: 47970,
    financas: 4,
    idolo: 'Bobô',
    nomeCompleto: 'Esporte Clube Bahia',
    titulos: {
      estadual: 49,
      brasileirao: 0,
      copaDoBrasil: 0,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
  {
    idTime: 5,
    nomeTime: 'Botafogo',
    forcaAtaque: 4,
    forcaDefesa: 3,
    torcida: 6,
    estadio: 'Estádio Nilton Santos',
    capacidadeEstadio: 48000,
    financas: 5,
    idolo: 'Garrincha',
    nomeCompleto: 'Botafogo de Futebol e Regatas',
    titulos: {
      estadual: 21,
      brasileirao: 0,
      copaDoBrasil: 0,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
  {
    idTime: 6,
    nomeTime: 'Corinthians',
    forcaAtaque: 6,
    forcaDefesa: 4,
    torcida: 10,
    estadio: 'Arena Corinthians',
    capacidadeEstadio: 49205,
    financas: 9,
    idolo: 'Sócrates',
    nomeCompleto: 'Sport Club Corinthians Paulista',
    titulos: {
      estadual: 30,
      brasileirao: 7,
      copaDoBrasil: 3,
      libertadores: 1,
      mundial: 2,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
  {
    idTime: 7,
    nomeTime: 'Coritiba',
    forcaAtaque: 3,
    forcaDefesa: 3,
    torcida: 4,
    estadio: 'Estádio Couto Pereira',
    capacidadeEstadio: 40600,
    financas: 3,
    idolo: 'Krüger',
    nomeCompleto: 'Coritiba Foot Ball Club',
    titulos: {
      estadual: 38,
      brasileirao: 1,
      copaDoBrasil: 1,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
  {
    idTime: 8,
    nomeTime: 'Cruzeiro',
    forcaAtaque: 5,
    forcaDefesa: 4,
    torcida: 7,
    estadio: 'Mineirão',
    capacidadeEstadio: 61846,
    financas: 6,
    idolo: 'Tostão',
    nomeCompleto: 'Cruzeiro Esporte Clube',
    titulos: {
      estadual: 38,
      brasileirao: 4,
      copaDoBrasil: 6,
      libertadores: 2,
      mundial: 2,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
  {
    idTime: 9,
    nomeTime: 'Cuiabá',
    forcaAtaque: 3,
    forcaDefesa: 2,
    torcida: 3,
    estadio: 'Arena Pantanal',
    capacidadeEstadio: 41780,
    financas: 2,
    idolo: 'Gonçalves',
    nomeCompleto: 'Cuiabá Esporte Clube',
    titulos: {
      estadual: 3,
      brasileirao: 0,
      copaDoBrasil: 0,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
  {
    idTime: 10,
    nomeTime: 'Flamengo',
    forcaAtaque: 9,
    forcaDefesa: 5,
    torcida: 10,
    estadio: 'Estádio do Maracanã',
    capacidadeEstadio: 78838,
    financas: 10,
    idolo: 'Zico',
    nomeCompleto: 'Clube de Regatas do Flamengo',
    titulos: {
      estadual: 36,
      brasileirao: 7,
      copaDoBrasil: 3,
      libertadores: 2,
      mundial: 3,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
  {
    idTime: 11,
    nomeTime: 'Fluminense',
    forcaAtaque: 7,
    forcaDefesa: 4,
    torcida: 6,
    estadio: 'Estádio do Maracanã',
    capacidadeEstadio: 78838,
    financas: 7,
    idolo: 'Telê Santana',
    nomeCompleto: 'Fluminense Football Club',
    titulos: {
      estadual: 31,
      brasileirao: 4,
      copaDoBrasil: 1,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
  {
    idTime: 12,
    nomeTime: 'Fortaleza',
    forcaAtaque: 5,
    forcaDefesa: 3,
    torcida: 5,
    estadio: 'Arena Castelão',
    capacidadeEstadio: 49103,
    financas: 5,
    idolo: 'Clodoaldo',
    nomeCompleto: 'Fortaleza Esporte Clube',
    titulos: {
      estadual: 42,
      brasileirao: 1,
      copaDoBrasil: 0,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
  {
    idTime: 13,
    nomeTime: 'Goiás',
    forcaAtaque: 4,
    forcaDefesa: 3,
    torcida: 4,
    estadio: 'Estádio Hailé Pinheiro',
    capacidadeEstadio: 16343,
    financas: 3,
    idolo: 'Túlio Maravilha',
    nomeCompleto: 'Goiás Esporte Clube',
    titulos: {
      estadual: 28,
      brasileirao: 0,
      copaDoBrasil: 0,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
  {
    idTime: 14,
    nomeTime: 'Grêmio',
    forcaAtaque: 7,
    forcaDefesa: 5,
    torcida: 8,
    estadio: 'Arena do Grêmio',
    capacidadeEstadio: 55000,
    financas: 7,
    idolo: 'Renato Gaúcho',
    nomeCompleto: 'Grêmio Foot-Ball Porto Alegrense',
    titulos: {
      estadual: 39,
      brasileirao: 2,
      copaDoBrasil: 5,
      libertadores: 3,
      mundial: 3,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
  {
    idTime: 15,
    nomeTime: 'Internacional',
    forcaAtaque: 7,
    forcaDefesa: 4,
    torcida: 7,
    estadio: 'Estádio Beira-Rio',
    nomeCompleto: 'Sport Club Internacional',
    capacidadeEstadio: 50090,
    financas: 7,
    idolo: 'Falcão',
    titulos: {
      estadual: 45,
      brasileirao: 3,
      copaDoBrasil: 1,
      libertadores: 3,
      mundial: 3,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
  {
    idTime: 16,
    nomeTime: 'Palmeiras',
    forcaAtaque: 8,
    forcaDefesa: 5,
    torcida: 9,
    estadio: 'Allianz Parque',
    nomeCompleto: 'Sociedade Esportiva Palmeiras',
    capacidadeEstadio: 43374,
    financas: 8,
    idolo: 'Ademir da Guia',
    titulos: {
      estadual: 23,
      brasileirao: 10,
      copaDoBrasil: 4,
      libertadores: 2,
      mundial: 2,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
  {
    idTime: 17,
    nomeTime: 'Bragantino',
    forcaAtaque: 4,
    forcaDefesa: 3,
    torcida: 4,
    estadio: 'Estádio Nabi Abi Chedid',
    nomeCompleto: 'Red Bull Bragantino',
    capacidadeEstadio: 15160,
    financas: 3,
    idolo: 'Tita',
    titulos: {
      estadual: 0,
      brasileirao: 1,
      copaDoBrasil: 0,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
  {
    idTime: 18,
    nomeTime: 'Santos',
    forcaAtaque: 6,
    forcaDefesa: 4,
    torcida: 7,
    estadio: 'Estádio Urbano Caldeira',
    capacidadeEstadio: 16050,
    financas: 6,
    nomeCompleto: 'Santos Futebol Clube',
    idolo: 'Pelé',
    titulos: {
      estadual: 22,
      brasileirao: 8,
      copaDoBrasil: 1,
      libertadores: 3,
      mundial: 3,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
  {
    idTime: 19,
    nomeTime: 'São Paulo',
    forcaAtaque: 7,
    forcaDefesa: 5,
    torcida: 9,
    estadio: 'Estádio do Morumbi',
    nomeCompleto: 'São Paulo Futebol Clube',
    capacidadeEstadio: 72593,
    financas: 8,
    idolo: 'Raí',
    titulos: {
      estadual: 21,
      brasileirao: 6,
      copaDoBrasil: 3,
      libertadores: 3,
      mundial: 3,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
  {
    idTime: 20,
    nomeTime: 'Vasco da Gama',
    forcaAtaque: 5,
    forcaDefesa: 4,
    torcida: 6,
    estadio: 'Estádio São Januário',
    capacidadeEstadio: 21111,
    financas: 5,
    idolo: 'Roberto Dinamite',
    nomeCompleto: 'Club de Regatas Vasco da Gama',
    titulos: {
      estadual: 24,
      brasileirao: 4,
      copaDoBrasil: 1,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [
      {
        idJogador: 23,
        idTime: 3,
        nomeJogador: 'Éverson',
        idadeJogador: 31,
        posicaoJogador: 'GOL',
        caracteristicaJogador: 'Ref/Col',
        valorJogador: 95000,
        golsJogador: 0,
        forcaJogador: 89,
      },
      {
        idJogador: 24,
        idTime: 3,
        nomeJogador: 'Réver',
        idadeJogador: 36,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Cab/Vel',
        valorJogador: 80000,
        golsJogador: 3,
        forcaJogador: 84,
      },
      {
        idJogador: 25,
        idTime: 3,
        nomeJogador: 'Guilherme Arana',
        idadeJogador: 24,
        posicaoJogador: 'LAT',
        caracteristicaJogador: 'Cru/Vel',
        valorJogador: 90000,
        golsJogador: 5,
        forcaJogador: 87,
      },
      {
        idJogador: 26,
        idTime: 3,
        nomeJogador: 'Allan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 85000,
        golsJogador: 6,
        forcaJogador: 86,
      },
      {
        idJogador: 27,
        idTime: 3,
        nomeJogador: 'Tchê Tchê',
        idadeJogador: 28,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Arm',
        valorJogador: 87000,
        golsJogador: 7,
        forcaJogador: 86,
      },
      {
        idJogador: 28,
        idTime: 3,
        nomeJogador: 'Savarino',
        idadeJogador: 30,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 88000,
        golsJogador: 10,
        forcaJogador: 87,
      },
      {
        idJogador: 29,
        idTime: 3,
        nomeJogador: 'Keno',
        idadeJogador: 32,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 95000,
        golsJogador: 12,
        forcaJogador: 89,
      },
      {
        idJogador: 30,
        idTime: 3,
        nomeJogador: 'Vargas',
        idadeJogador: 24,
        posicaoJogador: 'ATA',
        caracteristicaJogador: 'Fin/Dri',
        valorJogador: 92000,
        golsJogador: 11,
        forcaJogador: 88,
      },
      {
        idJogador: 31,
        idTime: 3,
        nomeJogador: 'Jair',
        idadeJogador: 27,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 83000,
        golsJogador: 4,
        forcaJogador: 85,
      },
      {
        idJogador: 32,
        idTime: 3,
        nomeJogador: 'Junior Alonso',
        idadeJogador: 29,
        posicaoJogador: 'ZAG',
        caracteristicaJogador: 'Des/Res',
        valorJogador: 85000,
        golsJogador: 2,
        forcaJogador: 85,
      },
      {
        idJogador: 33,
        idTime: 3,
        nomeJogador: 'Nathan',
        idadeJogador: 25,
        posicaoJogador: 'MEI',
        caracteristicaJogador: 'Dri/Fin',
        valorJogador: 81000,
        golsJogador: 5,
        forcaJogador: 83,
      },
    ],
  },
];
