import { Time } from '../model/time.model';

export const teams: Time[] = [
  {
    idTime: 1,
    nomeTime: 'América-MG',
    forcaAtaque: 3,
    forcaDefesa: 2,
    torcida: 4,
    estadio: 'Estádio Independência',
    capacidadeEstadio: 23018,
    financas: 3,
    idolo: 'Reinaldo',
    nomeCompleto: 'América Futebol Clube',
    titulos: {
      estadual: 16,
      brasileirao: 0,
      copaDoBrasil: 0,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 2,
    nomeTime: 'Athletico-PR',
    forcaAtaque: 6,
    forcaDefesa: 6,
    torcida: 6,
    estadio: 'Arena da baixada',
    capacidadeEstadio: 35000,
    financas: 5,
    idolo: 'Thiago Heleno',
    nomeCompleto: 'Clube Athletico Paranaense',
    titulos: {
      estadual: 16,
      brasileirao: 1,
      copaDoBrasil: 1,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 3,
    nomeTime: 'Atlético-MG',
    forcaAtaque: 8,
    forcaDefesa: 4,
    torcida: 8,
    estadio: 'Mineirão',
    capacidadeEstadio: 61846,
    financas: 8,
    idolo: 'Reinaldo',
    nomeCompleto: 'Clube Atlético Mineiro',
    titulos: {
      estadual: 47,
      brasileirao: 1,
      copaDoBrasil: 1,
      libertadores: 1,
      mundial: 1,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 4,
    nomeTime: 'Bahia',
    forcaAtaque: 4,
    forcaDefesa: 3,
    torcida: 5,
    estadio: 'Arena Fonte Nova',
    capacidadeEstadio: 47970,
    financas: 4,
    idolo: 'Bobô',
    nomeCompleto: 'Esporte Clube Bahia',
    titulos: {
      estadual: 49,
      brasileirao: 0,
      copaDoBrasil: 0,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 5,
    nomeTime: 'Botafogo',
    forcaAtaque: 4,
    forcaDefesa: 3,
    torcida: 6,
    estadio: 'Estádio Nilton Santos',
    capacidadeEstadio: 48000,
    financas: 5,
    idolo: 'Garrincha',
    nomeCompleto: 'Botafogo de Futebol e Regatas',
    titulos: {
      estadual: 21,
      brasileirao: 0,
      copaDoBrasil: 0,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 6,
    nomeTime: 'Corinthians',
    forcaAtaque: 6,
    forcaDefesa: 4,
    torcida: 10,
    estadio: 'Arena Corinthians',
    capacidadeEstadio: 49205,
    financas: 9,
    idolo: 'Sócrates',
    nomeCompleto: 'Sport Club Corinthians Paulista',
    titulos: {
      estadual: 30,
      brasileirao: 7,
      copaDoBrasil: 3,
      libertadores: 1,
      mundial: 2,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 7,
    nomeTime: 'Coritiba',
    forcaAtaque: 3,
    forcaDefesa: 3,
    torcida: 4,
    estadio: 'Estádio Couto Pereira',
    capacidadeEstadio: 40600,
    financas: 3,
    idolo: 'Krüger',
    nomeCompleto: 'Coritiba Foot Ball Club',
    titulos: {
      estadual: 38,
      brasileirao: 1,
      copaDoBrasil: 1,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 8,
    nomeTime: 'Cruzeiro',
    forcaAtaque: 5,
    forcaDefesa: 4,
    torcida: 7,
    estadio: 'Mineirão',
    capacidadeEstadio: 61846,
    financas: 6,
    idolo: 'Tostão',
    nomeCompleto: 'Cruzeiro Esporte Clube',
    titulos: {
      estadual: 38,
      brasileirao: 4,
      copaDoBrasil: 6,
      libertadores: 2,
      mundial: 2,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 9,
    nomeTime: 'Cuiabá',
    forcaAtaque: 3,
    forcaDefesa: 2,
    torcida: 3,
    estadio: 'Arena Pantanal',
    capacidadeEstadio: 41780,
    financas: 2,
    idolo: 'Gonçalves',
    nomeCompleto: 'Cuiabá Esporte Clube',
    titulos: {
      estadual: 3,
      brasileirao: 0,
      copaDoBrasil: 0,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 10,
    nomeTime: 'Flamengo',
    forcaAtaque: 9,
    forcaDefesa: 5,
    torcida: 10,
    estadio: 'Estádio do Maracanã',
    capacidadeEstadio: 78838,
    financas: 10,
    idolo: 'Zico',
    nomeCompleto: 'Clube de Regatas do Flamengo',
    titulos: {
      estadual: 36,
      brasileirao: 7,
      copaDoBrasil: 3,
      libertadores: 2,
      mundial: 3,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 11,
    nomeTime: 'Fluminense',
    forcaAtaque: 7,
    forcaDefesa: 4,
    torcida: 6,
    estadio: 'Estádio do Maracanã',
    capacidadeEstadio: 78838,
    financas: 7,
    idolo: 'Telê Santana',
    nomeCompleto: 'Fluminense Football Club',
    titulos: {
      estadual: 31,
      brasileirao: 4,
      copaDoBrasil: 1,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 12,
    nomeTime: 'Fortaleza',
    forcaAtaque: 5,
    forcaDefesa: 3,
    torcida: 5,
    estadio: 'Arena Castelão',
    capacidadeEstadio: 49103,
    financas: 5,
    idolo: 'Clodoaldo',
    nomeCompleto: 'Fortaleza Esporte Clube',
    titulos: {
      estadual: 42,
      brasileirao: 1,
      copaDoBrasil: 0,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 13,
    nomeTime: 'Goiás',
    forcaAtaque: 4,
    forcaDefesa: 3,
    torcida: 4,
    estadio: 'Estádio Hailé Pinheiro',
    capacidadeEstadio: 16343,
    financas: 3,
    idolo: 'Túlio Maravilha',
    nomeCompleto: 'Goiás Esporte Clube',
    titulos: {
      estadual: 28,
      brasileirao: 0,
      copaDoBrasil: 0,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 14,
    nomeTime: 'Grêmio',
    forcaAtaque: 7,
    forcaDefesa: 5,
    torcida: 8,
    estadio: 'Arena do Grêmio',
    capacidadeEstadio: 55000,
    financas: 7,
    idolo: 'Renato Gaúcho',
    nomeCompleto: 'Grêmio Foot-Ball Porto Alegrense',
    titulos: {
      estadual: 39,
      brasileirao: 2,
      copaDoBrasil: 5,
      libertadores: 3,
      mundial: 3,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 15,
    nomeTime: 'Internacional',
    forcaAtaque: 7,
    forcaDefesa: 4,
    torcida: 7,
    estadio: 'Estádio Beira-Rio',
    nomeCompleto: 'Sport Club Internacional',
    capacidadeEstadio: 50090,
    financas: 7,
    idolo: 'Falcão',
    titulos: {
      estadual: 45,
      brasileirao: 3,
      copaDoBrasil: 1,
      libertadores: 3,
      mundial: 3,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 16,
    nomeTime: 'Palmeiras',
    forcaAtaque: 8,
    forcaDefesa: 5,
    torcida: 9,
    estadio: 'Allianz Parque',
    nomeCompleto: 'Sociedade Esportiva Palmeiras',
    capacidadeEstadio: 43374,
    financas: 8,
    idolo: 'Ademir da Guia',
    titulos: {
      estadual: 23,
      brasileirao: 10,
      copaDoBrasil: 4,
      libertadores: 2,
      mundial: 2,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 17,
    nomeTime: 'Bragantino',
    forcaAtaque: 4,
    forcaDefesa: 3,
    torcida: 4,
    estadio: 'Estádio Nabi Abi Chedid',
    nomeCompleto: 'Red Bull Bragantino',
    capacidadeEstadio: 15160,
    financas: 3,
    idolo: 'Tita',
    titulos: {
      estadual: 0,
      brasileirao: 1,
      copaDoBrasil: 0,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 18,
    nomeTime: 'Santos',
    forcaAtaque: 6,
    forcaDefesa: 4,
    torcida: 7,
    estadio: 'Estádio Urbano Caldeira',
    capacidadeEstadio: 16050,
    financas: 6,
    nomeCompleto: 'Santos Futebol Clube',
    idolo: 'Pelé',
    titulos: {
      estadual: 22,
      brasileirao: 8,
      copaDoBrasil: 1,
      libertadores: 3,
      mundial: 3,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 19,
    nomeTime: 'São Paulo',
    forcaAtaque: 7,
    forcaDefesa: 5,
    torcida: 9,
    estadio: 'Estádio do Morumbi',
    nomeCompleto: 'São Paulo Futebol Clube',
    capacidadeEstadio: 72593,
    financas: 8,
    idolo: 'Raí',
    titulos: {
      estadual: 21,
      brasileirao: 6,
      copaDoBrasil: 3,
      libertadores: 3,
      mundial: 3,
    },
    jogadores: [],
    partidas: [],
  },
  {
    idTime: 20,
    nomeTime: 'Vasco da Gama',
    forcaAtaque: 5,
    forcaDefesa: 4,
    torcida: 6,
    estadio: 'Estádio São Januário',
    capacidadeEstadio: 21111,
    financas: 5,
    idolo: 'Roberto Dinamite',
    nomeCompleto: 'Club de Regatas Vasco da Gama',
    titulos: {
      estadual: 24,
      brasileirao: 4,
      copaDoBrasil: 1,
      libertadores: 0,
      mundial: 0,
    },
    jogadores: [],
    partidas: [],
  },
];
